# Overall Situation
theme_color: '#5e72e4' # Theme Color
show_customize_theme_color_picker: true # Allow users to customize theme colors
darkmode_autoswitch: alwayson # Automatically switch to night mode, Option: "false" uses Night Mode by default, "alwayson" uses Dark Mode by default, "system" follows the system, "time" switches with time
enable_amoled_dark: false # Night Mode style, "false" means gray and black, "true" means dark
card_radius: 4 # Default Card Corner Size
card_shadow: # Default Card Shadow Size, optional "small" and "big"
font: sans-serif # Default Font, option: "sans-serif" or "serif"
enable_headroom: false # Whether to automatically collapse the top bar when scrolling

# Top Bar
toolbar_icon: '' # The image address of the top bar icon. If left blank, it will not be displayed.
toolbar_icon_link: '' # Top bar icon link, jump when clicked
toolbar_title: '' # Top Column title, leave blank to follow blog title
toolbar_menu: # Top bar menu, supports secondary menu
  Home: /
  Secondary menu:
    Archive: /archives

# Banner
banner_title: '' # Banner Title, leave it blank to follow the blog title
enable_banner_title_typing_effect: false # Whether to enable Banner typing effect
theme.banner_typing_effect_interval: 100 # Banner typing interval length, unit ms/word
banner_subtitle: '' # Banner Subtitle, if left blank, it will not be displayed.
banner_background_url: '/assets/img/banner.jpg' # Banner Background image, if left blank, it will not be displayed.
banner_background_hide_shapes: false # Whether to hide the Banner Background Circle
banner_background_color_type: 'shape-primary' # Banner Gradient style, Banner Background image will cover this option, option value: shape-primary, shape-default, shape-dark, bg-gradient-success, bg-gradient-info, bg-gradient-warning, bg-gradient-danger

# Sidebar
sidebar_banner_title: '' # Sidebar Title, leave blank to follow blog title
sidebar_banner_subtitle: '' # Sidebar Subtitle, leave it blank to not display, set to --hitokoto-- Call Yiyan
sidebar_announcement: '' # Sidebar Announcement, if left blank, it will not be displayed.
leftbar_menu: # Menu at the top of the sidebar, supporting unlimited levels of menu nesting
  Home: /
  Archive: /archives
  Secondary menu:
    Third level menu:
      Home: /
sidebar_auther_image: '/assets/img/author.jpg' # Sidebar author avatar
sidebar_auther_name: 'Satoru' # Sidebar author name, leave blank to follow blog name
leftbar_author_links: # Sidebar author link list
  aaa: /
  bbb: /
  ccc: /
leftbar_friend_links: # Sidebar friend link list
  aaa: /
  bbb: /
  ccc: /

# Article
show_headindex_number: true # Whether the sidebar article table of contents displays chapter numbers
excerpt: true # Whether to display the article summary, if false, the full text will be displayed
first_image_as_thumbnail: false # Automatically select the first picture of the article as the featured picture
article_meta: categories|time|words|readingtime # Article Meta information list, separated by vertical bars, option: "time" publishing time, "edittime" editing time, "categories" categories, "read" reading volume, "words" word count, "readingtime" estimated reading time
reading_speed_cn: 300 # Number of Chinese words read per minute, used to calculate estimated reading time
reading_speed_en: 160 # Number of English words read per minute, used to calculate estimated reading time
donate_qrcode_url: '' # Donation QR code link address, if left blank, it will not be displayed
additional_content_after_post: '' # Append information at the end of the text, supports HTML, will not be displayed if left blank
article_header_style: default # Subtitle style within the article, option: default, 1, 2

# Background
page_background_url: '/assets/img/banner.jpg' # Page Background address. If left blank, there will be no page background.
page_background_dark_url: '/assets/img/banner.jpg' # Night Mode page Background address, leave it blank to follow day mode
page_background_opacity: 1 # Page Background opacity, decimal from 0 to 1
transparent_banner: true # Banner is made transparent. It is recommended to turn on this option if the background is set.
show_toolbar_mask: false # Top bar mask. If the background image affects the display contrast of the top bar text, it is recommended to turn it on.

# Floating Action Button
fab_show_darkmode_button: true # Whether to display the Day and Night Mode switching floating operation button
fab_show_settings_button: false # Whether to display Blog Settings floating action button
fab_show_gotocomment_button: false # Whether to display a floating action button that jumps to the Comment area

# Smooth Scrolling
smoothscroll: 1 # Option: disabled, 1, 1-pulse, 2, 3

# Zoomify
enable_zoomify: true # Whether to enable Zoomify image enlargement preview
zoomify_duration: 200 # Image enlargement animation duration
zoomify_easing: cubic-bezier(0.4,0,0,1) # Picture enlargement animation curve
zoomify_scale: 0.9 # The maximum percentage of the page size after the image is enlarged, decimal 0 ~ 1

# Lazyload
enable_lazyload: true # Whether to enable Lazyload
lazyload_threshold: 800 # How many pixels from the bottom of the page does the image scroll to before loading?
lazyload_effect: fadeIn # Picture display animation
lazyload_loading_style: 1 # Image loading animation, optional values ​​1 ~ 11, none

# Pangu.js
enable_pangu: false # Whether to enable Pangu.js to automatically use spaces to separate Chinese and English characters in articles

# Other
pjax_disabled: false # Whether to disable Pjax
enable_into_article_animation: false # Whether to enable entry animation
enable_mobile_scale: false # Whether to allow the mobile phone to zoom the page

# Footer
footer_html: '' # Footer HTML

# Mathematical Formula
math_render: '' # Mathematical formula rendering scheme. If left blank, it will not be rendered. Option: "mathjax3", "mathjax2", "katex"
mathjax_cdn_url: //cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js # Mathjax 3 CDN address
argon_mathjax_v2_cdn_url: //cdn.jsdelivr.net/npm/mathjax@2.7.5/MathJax.js?config=TeX-AMS_HTML # Mathjax 2 CDN address
katex_cdn_url: //cdn.jsdelivr.net/npm/katex@0.11.1/dist/ # Katex CDN address

# Code Highlighting
enable_code_highlight: true # Whether to enable Highlight.js code highlighting
code_theme: night-owl # Code highlighting theme

# Script
custom_html_head: '' # Header script, HTML
custom_html_foot: '' # Footer script, HTML

# Comment
utterances:
  enable: false # Whether to enable the Utterances comment system
  repo: ''
  issue_term: 'pathname'
  theme: 'photon-dark'
  cross_origin: 'anonymous'
gitalk:
  enable: false # Whether to enable the Gitalk comment system
  owner: ''
  repo: ''
  admin: ''
  clientID: ''
  clientSecret: ''
giscus: # https://giscus.app/
  enable: false # Whether to enable the Giscus comment system
  repo: ''
  repo_id: ''
  category: ''
  category_id: ''
  mapping: 'pathname'
  input_position: 'top'
  theme: 'dark'
  lang: 'en'
waline: # https://waline.js.org/guide/get-started.html
  enable: false # Whether to enable the Waline comment system
  server_url: '' 
twikoo: # https://twikoo.js.org
  enable: false # Whether to enable Twikoo comment system
  envID: ' '
  lang: 'zh-CN'

# Analyze
# Baidu statistics
baidu_analytics:
  enable: false # Whether to enable Baidu Statistics
  id: '' # hm.js? a string of characters after

# gtag google global netcode
# Google Analytics Universal Analytics(old) and Google Analytics 4 both use gtag
gtag:
  enable: false # Whether to enable gtag
  id: '' # Please include G- or UA-
